--Execute on server 2
--Customer Support 31023: SLC User Has {CH#} Issue

use [SLCProject]

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#10001016}","DefaultValue":null,"Id":10001016,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#10001016}","DefaultValue":null,"Id":10001016,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14923568;

update PCO SET OptionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000012}","DefaultValue":null,"Id":10001012,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000012}","DefaultValue":null,"Id":10001012,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14923555;

update PCO SET OptionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000047}","DefaultValue":null,"Id":10001037,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000047}","DefaultValue":null,"Id":10001037,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14923572;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000029}","DefaultValue":null,"Id":10001060,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000029}","DefaultValue":null,"Id":10001060,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14923562;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000031}","DefaultValue":null,"Id":10001071,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000031}","DefaultValue":null,"Id":10001071,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14923545;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"27 0000","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","MValue":null,"DefaultValue":null,"Id":0,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"GENERAL REQUIREMENTS FOR COMMUNICATIONS SYSTEMS","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14920384;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000543}","DefaultValue":null,"Id":10001012,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000543}","DefaultValue":null,"Id":10001012,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14920167;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"27 5119","MValue":null,"DefaultValue":null,"Id":10001037,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","MValue":null,"DefaultValue":null,"Id":0,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"SOUND MASKING SYSTEMS","MValue":null,"DefaultValue":null,"Id":10001037,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14920716;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000543}","DefaultValue":null,"Id":10001012,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000543}","DefaultValue":null,"Id":10001012,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14919613;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000546}","DefaultValue":null,"Id":10001016,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000546}","DefaultValue":null,"Id":10001016,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14920665;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"27 0000","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","MValue":null,"DefaultValue":null,"Id":0,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"GENERAL REQUIREMENTS FOR COMMUNICATIONS SYSTEMS","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14920848;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"27 0000","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","MValue":null,"DefaultValue":null,"Id":0,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"GENERAL REQUIREMENTS FOR COMMUNICATIONS SYSTEMS","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14920908;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"27 0000","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","MValue":null,"DefaultValue":null,"Id":0,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"GENERAL REQUIREMENTS FOR COMMUNICATIONS SYSTEMS","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14920352;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"27 0000","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","MValue":null,"DefaultValue":null,"Id":0,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"GENERAL REQUIREMENTS FOR COMMUNICATIONS SYSTEMS","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14920689;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"27 0000","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","MValue":null,"DefaultValue":null,"Id":0,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"GENERAL REQUIREMENTS FOR COMMUNICATIONS SYSTEMS","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14920578;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"27 0000","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","MValue":null,"DefaultValue":null,"Id":0,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"GENERAL REQUIREMENTS FOR COMMUNICATIONS SYSTEMS","MValue":null,"DefaultValue":null,"Id":10000997,"ValueJson":null,"MValueJson":null,"TempSortOrder":0.0,"IsdeletedSectionId":false,"IncludeSectionTitle":false,"PrevTrackValue":null,"PrevTrackValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14919905;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000559}","DefaultValue":null,"Id":10001037,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000559}","DefaultValue":null,"Id":10001037,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14920828

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000557}","DefaultValue":null,"Id":10001032,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000557}","DefaultValue":null,"Id":10001032,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14920639;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000556}","DefaultValue":null,"Id":10001030,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000556}","DefaultValue":null,"Id":10001030,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14919963;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000012}","DefaultValue":null,"Id":10001012,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000012}","DefaultValue":null,"Id":10001012,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14923234;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000031}","DefaultValue":null,"Id":10001071,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000031}","DefaultValue":null,"Id":10001071,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14923221;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000029}","DefaultValue":null,"Id":10001060,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000029}","DefaultValue":null,"Id":10001060,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14923223;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000057}","DefaultValue":null,"Id":10001059,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000057}","DefaultValue":null,"Id":10001059,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14924188;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000546}","DefaultValue":null,"Id":10001016,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000546}","DefaultValue":null,"Id":10001016,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14942783;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000582}","DefaultValue":null,"Id":10001076,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000582}","DefaultValue":null,"Id":10001076,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14942786;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000054}","DefaultValue":null,"Id":10001054,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000054}","DefaultValue":null,"Id":10001054,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14923857;

update PCO set optionJson = '[{"OptionTypeId":3,"OptionTypeName":"SectionID","SortOrder":1,"Value":"{\\id\\#1000057}","DefaultValue":null,"Id":10001059,"ValueJson":null},{"OptionTypeId":1,"OptionTypeName":"CustomText","SortOrder":2,"Value":"-","DefaultValue":null,"Id":0,"ValueJson":null},{"OptionTypeId":10,"OptionTypeName":"SectionTitle","SortOrder":3,"Value":"{\\t\\#1000057}","DefaultValue":null,"Id":10001059,"ValueJson":null}]'
from ProjectChoiceOption PCO WITH(NOLOCK)  WHERE SegmentChoiceId = 14923856;

