create table #t(CountryId INT, CurrencyName nvarchar(255), CurrencyDigitalCode nvarchar(5), CurrencyAbbreviation nvarchar(255), CurrencySymbol nvarchar(255))
GO

INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (2, N'Afghani', N'971', N'AFN', N'Af')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (3, N'Lek', N'008', N'ALL', N'L')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (4, N'Algerian Dinar', N'012', N'DZD', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (5, N'US Dollar', N'840', N'USD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (6, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (7, N'Kwanza', N'973', N'AOA', N'Kz')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (8, N'East Caribbean Dollar', N'951', N'XCD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (10, N'East Caribbean Dollar', N'951', N'XCD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (11, N'Argentine Peso', N'032', N'ARS', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (12, N'Armenian Dram', N'051', N'AMD', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (13, N'Aruban Guilder/ Florin', N'533', N'AWG', N'ƒ')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (14, N'Australian Dollar', N'036', N'AUD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (15, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (16, N'Azerbaijanian Manat', N'944', N'AZN', N'???')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (17, N'Bahamian Dollar', N'044', N'BSD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (18, N'Bahraini Dinar', N'048', N'BHD', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (19, N'Taka', N'050', N'BDT', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (20, N'Barbados Dollar', N'052', N'BBD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (21, N'Belarussian Ruble', N'974', N'BYR', N'Br')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (22, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (23, N'Belize Dollar', N'084', N'BZD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (24, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (25, N'Bermudian Dollar', N'060', N'BMD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (26, N'Ngultrum', N'064', N'BTN', N'Nu.(ngultrum);Ch.(chhertum)')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (27, N'Boliviano', N'068', N'BOB', N'Bs.')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (28, N'United States dollar', N'840', N'USD', N'$(dollar);¢(penny)')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (29, N'Konvertibilna Marka', N'977', N'BAM', N'??')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (30, N'Pula', N'072', N'BWP', N'P')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (32, N'Brazilian Real', N'986', N'BRL', N'R$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (33, N'Pound Sterling', N'826', N'GBP', N'£')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (35, N'Singapore Dollar', N'702', N'SGD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (36, N'Bulgarian Lev', N'975', N'BGN', N'??')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (37, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (38, N'Burundi Franc', N'108', N'BIF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (39, N'Cabo Verde Escudo', N'132', N'CVE', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (40, N'Riel', N'116', N'KHR', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (41, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (42, N'Canadian Dollar', N'124', N'CAD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (43, N'Cayman Islands Dollar', N'136', N'KYD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (44, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (45, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (46, N'Chilean Peso', N'152', N'CLP', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (47, N'Yuan', N'156', N'CNY', N'¥')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (50, N'Colombian Peso', N'170', N'COP', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (51, N'Comoro Franc', N'174', N'KMF', N'CF')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (52, N'Congolese Franc', N'976', N'CDF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (53, N'New Zealand Dollar', N'554', N'NZD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (54, N'Costa Rican Colon', N'188', N'CRC', N'¢')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (55, N'Croatian Kuna', N'191', N'HRK', N'Kn')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (56, N'Cuban Peso', N'192', N'CUP', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (58, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (59, N'Czech Koruna', N'203', N'CZK', N'Kc')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (60, N'US Dollar', N'978', N'USD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (61, N'Danish Krone', N'208', N'DKK', N'kr')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (62, N'Djibouti Franc', N'262', N'DJF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (63, N'East Caribbean Dollar', N'951', N'XCD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (64, N'Dominican Peso', N'214', N'DOP', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (65, N'United States dollar', N'840', N'USD', N'$(dollar);¢(penny)')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (66, N'Egyptian Pound', N'818', N'EGP', N'£')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (67, N'United States dollar', N'840', N'USD', N'$(dollar);¢(penny)')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (68, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (69, N'Nakfa', N'232', N'ERN', N'Nfk')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (70, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (71, N'Ethiopian Birr', N'230', N'ETB', N'Br')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (75, N'Fiji Dollar', N'242', N'FJD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (76, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (77, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (79, N'CFP Franc', N'953', N'XPF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (81, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (82, N'Dalasi', N'270', N'GMD', N'D')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (83, N'Lari', N'981', N'GEL', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (84, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (85, N'Cedi', N'936', N'GHS', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (86, N'Gibraltar Pound', N'292', N'GIP', N'£')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (87, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (88, N'Danish Krone', N'208', N'DKK', N'kr')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (89, N'East Caribbean Dollar', N'951', N'XCD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (92, N'Quetzal', N'320', N'GTQ', N'Q')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (94, N'Guinea Franc', N'324', N'GNF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (95, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (96, N'Guyana Dollar', N'328', N'GYD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (97, N'Gourde', N'332', N'HTG', N'G')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (98, N'Jordanian Dinar', N'400', N'JOD', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (100, N'Lempira', N'340', N'HNL', N'L')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (101, N'Hong Kong Dollar', N'344', N'HKD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (102, N'Forint', N'348', N'HUF', N'Ft')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (103, N'Iceland Krona', N'352', N'ISK', N'Kr')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (104, N'Indian Rupee', N'356', N'INR', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (105, N'Rupiah', N'360', N'IDR', N'Rp')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (106, N'Iranian Rial', N'364', N'IRR', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (107, N'Iraqi Dinar', N'368', N'IQD', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (108, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (110, N'New Israeli Shekel', N'376', N'ILS', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (111, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (112, N'West African CFA franc', N'950', N'XOF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (113, N'Jamaican Dollar', N'388', N'JMD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (114, N'Yen', N'392', N'JPY', N'¥')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (116, N'Tenge', N'398', N'KZT', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (117, N'Kenyan Shilling', N'404', N'KES', N'Sh')
GO
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (118, N'Australian Dollar', N'036', N'AUD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (119, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (120, N'Kuwaiti Dinar', N'414', N'KWD', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (121, N'Som', N'417', N'KGS', N'som')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (122, N'Kip', N'418', N'LAK', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (123, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (124, N'Lebanese Pound', N'422', N'LBP', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (125, N'Loti', N'426', N'LSL', N'L')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (126, N'Liberian Dollar', N'430', N'LRD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (127, N'Libyan Dinar', N'434', N'LYD', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (128, N'Swiss Franc', N'756', N'CHF', N'CHF(francs)')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (129, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (130, N'Pataca', N'446', N'MOP', N'P')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (131, N'Denar', N'807', N'MKD', N'???')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (132, N'Malagasy Ariary', N'969', N'MGA', N'Ar')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (133, N'Kwacha', N'454', N'MWK', N'MK')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (134, N'Malaysian Ringgit', N'458', N'MYR', N'RM')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (135, N'Rufiyaa', N'462', N'MVR', N'?.')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (136, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (137, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (140, N'Ouguiya', N'478', N'MRO', N'UM')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (141, N'Mauritius Rupee', N'480', N'MUR', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (143, N'Mexican Peso', N'484', N'MXN', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (144, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (145, N'Tugrik', N'496', N'MNT', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (146, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (147, N'East Caribbean Dollar', N'951', N'XCD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (148, N'Moroccan Dirham', N'504', N'MAD', N'?.?.')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (149, N'Metical', N'943', N'MZN', N'MTn')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (150, N'Kyat', N'104', N'MMK', N'K')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (151, N'Namibia Dollar', N'516', N'NAD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (152, N'Australian Dollar', N'036', N'AUD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (153, N'Nepalese Rupee', N'524', N'NPR', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (154, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (155, N'CFP Franc', N'953', N'XPF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (156, N'New Zealand Dollar', N'554', N'NZD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (157, N'Cordoba Oro', N'558', N'NIO', N'C$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (158, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (159, N'Naira', N'566', N'NGN', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (160, N'New Zealand Dollar', N'554', N'NZD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (162, N'North Korean Won', N'408', N'KPW', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (163, N'US Dollar', N'840', N'USD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (164, N'Norwegian Krone', N'578', N'NOK', N'kr')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (165, N'Rial Omani', N'512', N'OMR', N'?.?.')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (166, N'Pakistan Rupee', N'586', N'PKR', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (167, N'US Dollar', N'840', N'USD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (168, N'New Israeli Shekel', N'376', N'ILS', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (169, N'Balboa', N'590', N'PAB', N'B/.')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (170, N'Kina', N'598', N'PGK', N'K')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (171, N'Guarani', N'600', N'PYG', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (172, N'Nuevo Sol', N'604', N'PEN', N'S/.')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (173, N'Philippine Peso', N'608', N'PHP', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (175, N'PZloty', N'985', N'PLN', N'zl')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (176, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (177, N'US Dollar', N'840', N'USD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (178, N'Qatari Rial', N'634', N'QAR', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (180, N'Won', N'410', N'KRW', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (181, N'Lithuanian Litas', N'440', N'LTL', N'Lt(Litas),ct(Centas)')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (182, N'Moldovan Leu', N'498', N'MDL', N'lei')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (183, N'Congolese Franc', N'976', N'CDF', N'FC')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (184, N'Leu', N'946', N'RON', N'L')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (185, N'Russian Ruble', N'643', N'RUB', N'?.')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (186, N'Rwanda Franc', N'646', N'RWF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (187, N'Dobra', N'678', N'STD', N'Db')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (188, N'Saint Helena Pound', N'654', N'SHP', N'£')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (189, N'East Caribbean Dollar', N'951', N'XCD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (191, N'Euro', N'978', N'EUR', N'€(euro);c(cent)')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (192, N'East Caribbean Dollar', N'951', N'XCD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (194, N'Tala', N'882', N'WST', N'T')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (195, N'Euro', N'978', N'EUR', N'$(dollar),cent')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (196, N'Saudi Riyal', N'682', N'SAR', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (197, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (198, N'Serbian Dinar', N'941', N'RSD', N'din')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (199, N'Seychelles Rupee', N'690', N'SCR', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (200, N'Leone', N'694', N'SLL', N'Le')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (201, N'Brunei Dollar Brunei', N'096', N'BND', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (203, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (204, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (205, N'Solomon Islands Dollar', N'090', N'SBD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (206, N'Somali Shilling', N'706', N'SOS', N'Sh')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (207, N'Rand', N'710', N'ZAR', N'R')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (210, N'Euro', N'978', N'EUR', N'€')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (211, N'Sri Lanka Rupee', N'144', N'LKR', N'Rs')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (212, N'East Caribbean Dollar', N'951', N'XCD', N'$(dollar),cent')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (213, N'Sudanese Pound', N'938', N'SDG', N'£')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (214, N'Suriname Dollar', N'968', N'SRD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (215, N'Norwegian Krone', N'578', N'NOK', N'kr')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (216, N'Lilangeni', N'748', N'SZL', N'L')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (217, N'Swedish Krona', N'752', N'SEK', N'kr')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (218, N'Swiss Franc', N'756', N'CHF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (219, N'Syrian Pound', N'760', N'SYP', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (220, N'Taiwan Dollar', N'901', N'TWD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (221, N'Somoni', N'972', N'TJS', N'??')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (222, N'Tanzanian Shilling', N'834', N'TZS', N'Sh')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (223, N'Baht', N'764', N'THB', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (224, N'CFA Franc BCEAO', N'950', N'XAF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (225, N'New Zealand Dollar', N'554', N'NZD', N'$(dollar);c(cent)')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (226, N'Pa’anga', N'776', N'TOP', N'T$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (227, N'Trinidad and Tobago Dollar', N'780', N'TTD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (228, N'Tunisian Dinar', N'788', N'TND', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (229, N'Turkish Lira', N'949', N'TRY', N'£')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (230, N'Manat', N'934', N'TMT', N'm')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (231, N'US Dollar', N'840', N'USD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (232, N'Australian Dollar', N'036', N'AUD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (235, N'Uganda Shilling', N'800', N'UGX', N'Sh')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (236, N'Hryvnia', N'980', N'UAH', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (237, N'UAE Dirham', N'784', N'AED', N'?.?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (238, N'Pound Sterling', N'826', N'GBP', N'£(pound);p(penny)')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (239, N'US Dollar', N'840', N'USD', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (240, N'Peso Uruguayo', N'858', N'UYU', N'$')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (241, N'Uzbekistan Sum', N'860', N'UZS', N'som')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (242, N'Vatu', N'548', N'VUV', N'Vt')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (244, N'Bolivar Fuerte', N'937', N'VEF', N'Bs.F.')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (245, N'Dong', N'704', N'VND', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (246, N'CFP Franc', N'953', N'XPF', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (248, N'Yemeni Rial', N'886', N'YER', N'?')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (249, N'Zambian Kwacha', N'967', N'ZMW', N'ZK')
INSERT INTO #t ([CountryId], [CurrencyName], [CurrencyDigitalCode], [CurrencyAbbreviation], [CurrencySymbol]) VALUES (250, N'Zimbabwe Dollar', N'932', N'ZWL', N'$')
GO

UPDATE c
SET c.CurrencyName=t.CurrencyName,
	c.CurrencyDigitalCode=t.CurrencyDigitalCode,
	c.CurrencyAbbreviation=t.CurrencyAbbreviation,
	c.CurrencySymbol=t.CurrencySymbol
from LuCountry c INNER join #t t
ON c.CountryId=t.CountryId

