Use SLCProject
GO

DROP INDEX [dbo].[ProjectSection].ProjectSection_ProjectId_CustomerId
DROP INDEX [SelectedChoiceOption].CSIx_SelectedChoiceOption_Include
DROP INDEX [dbo].[ProjectSegmentStatus].CIX_ProjectSegmentStatus_SectionId_ProjectId_CustomerId
DROP INDEX [dbo].[ProjectSegmentStatus].CIX_ProjectSegmentStatus_SegmentStatusTypeId
DROP INDEX [dbo].[ProjectSegmentLink].NCIX_ProjectSegmentLink_CustomerId