truncate table [dbo].LuProjectRequirementTag
DBCC CHECKIDENT('LuProjectRequirementTag', RESEED, 0)

SET IDENTITY_INSERT [dbo].[LuProjectRequirementTag] ON 

INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (1, N'NA', N'None', 1, 1, 0)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (2, N'NP', N'Non-Printing', 2, 1, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (3, N'NS', N'Non-Selectable', 3, 1, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (4, N'CT', N'Certificate', 4, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (5, N'DC', N'Design Calculations', 5, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (6, N'FR', N'Field Report', 6, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (7, N'FT', N'Independent Agency Field Testing', 7, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (8, N'II', N'Installation Instructions', 8, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (9, N'IQ', N'Installer Qualifications', 9, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (10, N'XM', N'Maintenance Materials', 10, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (11, N'ML', N'Manufacturer Listing', 11, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (12, N'MQ', N'Manufacturer Qualifications', 12, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (13, N'MO', N'Mock-Up', 13, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (14, N'OM', N'Operation & Maintenance Data', 14, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (15, N'PI', N'Preinstallation Meeting', 15, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (16, N'PL', N'Product', 16, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (17, N'PD', N'Product Data Submittal', 17, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (18, N'PE', N'Professional Engineer Design', 18, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (19, N'PR', N'Project Record Documents', 19, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (20, N'PP', N'Proprietary Product', 20, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (21, N'QS', N'Qualifications Statement', 21, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (22, N'RS', N'Reference Text Segment', 22, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (23, N'RT', N'References Title', 23, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (24, N'RE', N'Related Requirements Paragraph', 24, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (25, N'ST', N'Related Requirements Title', 25, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (26, N'SA', N'Samples', 26, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (27, N'SD', N'Shop Drawings', 27, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (28, N'SQ', N'Source Quality Control', 28, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (29, N'LR', N'Sustainable Design Documentation', 29, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (30, N'TR', N'Test Report', 30, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (31, N'WE', N'Warranty, Executed', 31, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (32, N'WT', N'Warranty, Special', 32, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (33, N'WS', N'Warranty, Specimen', 33, 2, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (34, N'S1', N'Proposal Phase Submittal', 34, 3, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (35, N'S2', N'Preliminary Phase', 35, 3, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (36, N'S3', N'Design Development Phase', 36, 3, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (37, N'S4', N'Construction Documents Phase', 37, 3, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (38, N'S5', N'Construction Phase', 38, 3, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (39, N'S6', N'Closeout Phase', 39, 3, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (40, N'S7', N'Occupancy Phase', 40, 3, 1)
INSERT [dbo].[LuProjectRequirementTag] ([RequirementTagId], [TagType], [Description], [SortOrder], [CategoryId], [IsActive]) VALUES (41, N'MT', N'Manufacturer Listing', 41, 2, 1)
SET IDENTITY_INSERT [dbo].[LuProjectRequirementTag] OFF

DBCC CHECKIDENT('LuProjectRequirementTag', RESEED, 41)
