truncate table [dbo].LuProjectDiscipline
DBCC CHECKIDENT('LuProjectDiscipline', RESEED, 0)

SET IDENTITY_INSERT [dbo].[LuProjectDiscipline] ON
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (1, N'Comprehensive', 1, 1, 1, 1)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (2, N'Architectural', 1, 1, 2, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (3, N'Civil Engineering', 1, 1, 3, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (4, N'Mechanical/Electrical', 1, 1, 4, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (5, N'Landscape Architecture', 1, 1, 5, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (6, N'Structural Engineering', 1, 1, 6, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (7, N'Design Criteria', 1, 1, 7, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (8, N'Waste Water', 1, 1, 8, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (9, N'The Basic', 1, 1, 9, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (10, N'Complete (EN)', 1, 2, 1, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (11, N'Air Transportation (EN)', 1, 2, 2, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (12, N'Architectural (EN)', 1, 2, 3, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (13, N'Building Services (EN)', 1, 2, 4, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (14, N'Conservation (EN)', 1, 2, 5, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (15, N'Electrical Engineering (EN)', 1, 2, 6, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (16, N'Heavy Civil Engineering (EN)', 1, 2, 7, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (17, N'Interior Design (EN)', 1, 2, 8, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (18, N'Landscape Architecture (EN)', 1, 2, 9, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (19, N'Landscape Architecture Pro (EN)', 1, 2, 10, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (20, N'Mechanical & Electrical Engineering (EN)', 1, 2, 11, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (21, N'Mechanical Engineering (EN)', 1, 2, 12, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (22, N'Mechanical Engineering Pro (EN)', 1, 2, 13, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (23, N'Performance (EN)', 1, 2, 14, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (24, N'Performance Pro Library (EN)', 1, 2, 15, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (25, N'Structural Engineering (EN)', 1, 2, 16, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (26, N'Complete (FR)', 1, 3, 1, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (27, N'Air Transportation (FR)', 1, 3, 2, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (28, N'Architectural (FR)', 1, 3, 3, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (29, N'Building Services (FR)', 1, 3, 4, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (30, N'Conservation (FR)', 1, 3, 5, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (31, N'Electrical Engineering (FR)', 1, 3, 6, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (32, N'Heavy Civil Engineering (FR)', 1, 3, 7, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (33, N'Interior Design (FR)', 1, 3, 8, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (34, N'Landscape Architecture (FR)', 1, 3, 9, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (35, N'Landscape Architecture Pro (FR)', 1, 3, 10, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (36, N'Mechanical & Electrical Engineering (FR)', 1, 3, 11, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (37, N'Mechanical Engineering (FR)', 1, 3, 12, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (38, N'Mechanical Engineering Pro (FR)', 1, 3, 13, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (39, N'Performance (FR)', 1, 3, 14, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (40, N'Performance Pro Library (FR)', 1, 3, 15, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (41, N'Structural Engineering (FR)', 1, 3, 16, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (42, N'Free', 1, 1, 10, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (43, N'Comprehensive', 1, 4, 1, 1)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (44, N'Architectural', 1, 4, 2, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (45, N'Civil Engineering', 1, 4, 3, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (46, N'Mechanical/Electrical', 1, 4, 4, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (47, N'Landscape Architecture', 1, 4, 5, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (48, N'Structural Engineering', 1, 4, 6, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (49, N'Design Criteria', 1, 4, 7, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (50, N'Waste Water', 1, 4, 8, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (51, N'The Basic', 1, 4, 9, 0)
INSERT [dbo].[LuProjectDiscipline] ([Disciplineld], [Name], [IsActive], [MasterDataTypeId], [DisplayOrder], [IsBundle]) VALUES (52, N'Free', 1, 4, 10, 0)
SET IDENTITY_INSERT [dbo].[LuProjectDiscipline] OFF

DBCC CHECKIDENT('LuProjectDiscipline', RESEED, 52)