USE [SLCProject]
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ImportDocLibrary' AND COLUMN_NAME = 'A_DocLibraryId')
BEGIN
	ALTER TABLE ImportDocLibrary
	ADD A_DocLibraryId INT NULL
END;