
CREATE TABLE LuProjectAccessType
(
ProjectAccessTypeId  INT IDENTITY(1,1),
[Name] NVARCHAR(100) NOT NULL,
[Description] NVARCHAR(500) NULL,
IsActive BIT NOT NULL
 CONSTRAINT [PK_LuProjectAccessType] PRIMARY KEY CLUSTERED 
(
	ProjectAccessTypeId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO