USE [SLCProject]
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UpdateStatisticsLog' AND COLUMN_NAME = 'JobType')
BEGIN
	ALTER TABLE UpdateStatisticsLog
	ADD JobType VARCHAR(50)
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UpdateStatisticsLog' AND COLUMN_NAME = 'IndexName')
BEGIN
	ALTER TABLE UpdateStatisticsLog
	ADD IndexName VARCHAR(100)
END;