use [SLCProject_SqlSlcOp004]
go
/*
	server name : SLCProject_SqlSlcOp004
	Customer Support 57044: SLC: Data Exporting Incorrectly
*/

UPDATE PS SET SegmentDescription = '1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;<a href="http://www.arcomnet.com/sustainable_design.aspx?topic=7">Product Data</a>: For recycled content, indicating postconsumer and preconsumer recycled content and cost.' FROM ProjectSegment PS WITH(NOLOCK)  where SegmentStatusId = 973424506 and SectionId = 19272041 and ProjectId = 15722 and CustomerId = 3108
UPDATE PS SET SegmentDescription = 'Samples: Submit two (2) samples of each type of wall texture specified for approval prior to application of texture.' FROM ProjectSegment PS WITH(NOLOCK)  where SegmentStatusId = 973424504 and SectionId = 19272041 and ProjectId = 15722 and CustomerId = 3108
UPDATE PS SET SegmentDescription = '4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; <a href="http://www.arcomnet.com/sustainable_design.aspx?topic=14">Product Data</a>: For interior products indicating compliance with General Emissions evaluation.' FROM ProjectSegment PS WITH(NOLOCK)  where SegmentStatusId = 973424509 and SectionId = 19272041 and ProjectId = 15722 and CustomerId = 3108
UPDATE PS SET SegmentDescription = '3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; <a href="http://www.arcomnet.com/sustainable_design.aspx?topic=13">Product Data</a>: For adhesives and sealants indicating compliance with General Emissions evaluation and VOC content requirements.' FROM ProjectSegment PS WITH(NOLOCK)  where SegmentStatusId = 973424508 and SectionId = 19272041 and ProjectId = 15722 and CustomerId = 3108
UPDATE PS SET SegmentDescription = '2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.arcomnet.com/sustainable_design.aspx?topic=8">Product Certificates</a>: For regional materials, indicating location of material manufacturer and point of extraction, harvest, or recovery for each raw material. Include distance to Project and cost for each regional material.' FROM ProjectSegment PS WITH(NOLOCK)  where SegmentStatusId = 973424507 and SectionId = 19272041 and ProjectId = 15722 and CustomerId = 3108
UPDATE PS SET SegmentDescription = 'a.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Environmental product Declarations:' FROM ProjectSegment PS WITH(NOLOCK)  where SegmentStatusId = 973424511 and SectionId = 19272041 and ProjectId = 15722 and CustomerId = 3108
UPDATE PS SET SegmentDescription = '5/8” heat-cured, acrylic coated, fiberglass faced sheet with moisture resistant core containing no asbestos or formaldehyde.' FROM ProjectSegment PS WITH(NOLOCK)  where SegmentStatusId = 973424513 and SectionId = 19272041 and ProjectId = 15722 and CustomerId = 3108
UPDATE PS SET SegmentDescription = 'b.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Material Ingredients – Documentation demonstrating the chemical inventory of the product to at least 0.1% (1000ppm).' FROM ProjectSegment PS WITH(NOLOCK)  where SegmentStatusId = 973424512 and SectionId = 19272041 and ProjectId = 15722 and CustomerId = 3108
UPDATE PS SET SegmentDescription = 'AZ SFB Low-VOC Design Submittals:' FROM ProjectSegment PS WITH(NOLOCK)  where SegmentStatusId = 973424505 and SectionId = 19272041 and ProjectId = 15722 and CustomerId = 3108
UPDATE PS SET SegmentDescription = '5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Building Product Disclosure Requirements: To encourage the use of building products that are working to minimize their environmental and health impacts, preference will be given to products with publicly available information:' FROM ProjectSegment PS WITH(NOLOCK)  where SegmentStatusId = 973424510 and SectionId = 19272041 and ProjectId = 15722 and CustomerId = 3108